### PR TITLE
Throttle progress-bar updates, increases performance by 5x

### PR DESCRIPTION
**Pull request by paullovessearch**
Also shows the size of the batches for in es-import-bulk.

### CODE REVIEW

**Comment by paullovessearch** [comment]
Okay, so this is the first major pull request I have ever done. I have tested it on my computer several times and everything is OK. Is there any other sort of unit tests I need to update?

I manage a number of search engine consultants, and so I'm hoping to recommend these tools for exporting and importing from Elasticsearch. They are wicked fast, I am getting ~4000 DPS on export and ~1730 DPS on import, with the --quieter option.

**Comment by skratchdot** [comment]
This is great!  I'm going to take a better look tomorrow and pull it in.  Unfortunately, there are no unit or integration tests in this lib.  It was something I whipped together quickly at my last job (because all the other exporters I used were too slow- or timed out on larger datasets).  I'm all for a performance increase.

Also, I haven't been using ES recently, so I'm not sure how out of date this lib is (or if there are better ones to recommend at this point).  I've been wanting to setup a local env, and get some tests written for this lib.  I might try to do that soon.

From a quick look at this PR, I notice 2 things:
- I don't think it will pass the `gulp lint` checks (which isn't a huge deal- I can fix that later)
- I notice a hard coded `10000`, but a cli configurable `20000`. Aren't those values tied together? Should the `10000` be calculated?  I also might be missing something b/c it's very late/early for me (and I'm tired)!

So thanks for taking the time to work on this!  I will check it out again soon (when I'm not so tired).  You'll also need to fix the merge conflicts before I can pull this in (I'm guessing it's b/c I already pulled in your last PR, so a quick `git pull --rebase upstream master; git push origin master` should fix it for you [assuming you have my repo setup as a remote named `upstream`]).

**Comment by paullovessearch** [comment]
I think I fixed the merge conflicts (again, all this is new to me, so let me know if I screwed something up).
The other import/export tool I found is "elasticdump", but they removed the "--bulk" option in the most recent version, so it's so much slower. Even with the --bulk (going back to the previous version) it's still about 5x slower than your tools.
All this started because we are starting to get more and more exported indexes from our customers. Elasticsearch snapshots are a less reliable way to transfer indexes than these import/export tools. Also, the import/export allows us to write JavaScript programs to manipulate the _source as necessary to try different index structures to see how they affect memory and performance.
Anyway, we got some 9.5m records from this one customer and the indexing took over 30 hours! Ack. So I went around looking for some faster tools and found yours. And now I'm getting ~1650 DPS in import and ~4000 DPS on export. So that's pretty amazing.
I also like yours better because it exports the standard Elasticsearch bulk format, so I could probably create a shell script to import your files with cURL. Elasticdump has their own, hybrid format.
Anyway, if you don't mind, I might add the "--skip" option and the "--index" option to import (import to new indexes) at some point in the future. Also it would be nice to export from one URL and then import to another URL (direct from server to server)... but that's a longer-term item.

**Comment by skratchdot** [comment]
The url->url (server->server) import/export is something I wanted to add originally, but the file dump was most important to me (at the beginning).  This lib could definitely use a re-write.  I think re-working the architecture to allow for different sources/drivers won't be too difficult (file vs url vs ???).  I'll try to take a look at cleaning up this library soon.

**Pull request merged**
