### PR TITLE
Support option requestTimeout for bulk importing

### PR DESCRIPTION
**Pull request by duylam**
Allow to customize `requestTimeout` ES client option for `es-import-bulk.js` in case ES cluster is insufficient to proceed the importing request within default timeout (30 seconds)

### CODE REVIEW

**Comment by duylam** [comment]
Hello ?

**Comment by skratchdot** [comment]
Thanks. I will pull this in.

**Comment by skratchdot** [comment]
@duylam - new version published: 4.0.1

**Comment by duylam** [comment]
Thanks @skratchdot

**Pull request merged**
